ALTER TABLE players
  ADD COLUMN IF NOT EXISTS heat INT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS civis INT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS alignment_active ENUM('NEUTRAL','HEAT','CIVIS') NOT NULL DEFAULT 'NEUTRAL';

CREATE TABLE IF NOT EXISTS respawn_workshop_orders (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  citizenid VARCHAR(50) NOT NULL,
  branch ENUM('HEAT','CIVIS') NOT NULL,
  family VARCHAR(64) NOT NULL,
  level  INT NOT NULL,
  cost   INT NOT NULL DEFAULT 0,
  mats   JSON NULL,
  status ENUM('QUEUED','READY','DELIVERED','CANCELLED') NOT NULL DEFAULT 'QUEUED',
  started_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ready_at   TIMESTAMP NULL,
  INDEX (citizenid), INDEX(status)
);
