version: "3.8"

services:
  mariadb:
    image: mariadb:10.11
    container_name: respawn_mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: Europe/Madrid
    ports:
      - "3306:3306"
    volumes:
      - ./mariadb-data:/var/lib/mysql
      - ./mariadb-init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 10
